# NUMPY

In [3]:
#heterogenous 1D array
arr = [1,2,"a",3,"b"]


In [8]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
x*y


array([ 4, 10, 18])

In [9]:
import numpy as np
#define
just_a_list = [1,2,3]
#show
just_a_list

[1, 2, 3]

In [10]:
import numpy as np
just_a_list = [1,2,3]
np.array(just_a_list)

array([1, 2, 3])

In [11]:
import numpy as np
#define
just_a_matrix = [[1,2,3],[4,5,6],[7,8,9]]
#show
just_a_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
import numpy as np
#define
just_a_matrix = [[1,2,3],[4,5,6],[7,8,9]]
#show
np.array(just_a_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
import numpy as np
np.arange(0,20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
import numpy as np
#step size of 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
import numpy as np
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
import numpy as np
np.ones(4)


array([1., 1., 1., 1.])

In [18]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
import numpy as np
#generates three numbers
#between range 0 to 10
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
import numpy as np
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [22]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
import numpy as np
np.random.rand(2)


array([0.75261764, 0.40355455])

In [24]:
import numpy as np
np.random.rand(3,3)


array([[0.47391322, 0.96980881, 0.03119947],
       [0.70224136, 0.46984861, 0.13303997],
       [0.52404209, 0.0291802 , 0.57177518]])

In [25]:
import numpy as np
np.random.randn(2)

array([0.03599606, 1.42227488])

In [26]:
import numpy as np
np.random.randn(4,4)

array([[-0.23232824,  1.52396446,  1.27804697,  1.54168661],
       [ 0.18651272, -1.01737444,  0.60560337,  0.18635974],
       [-0.34886112, -1.64104164, -0.33407226,  0.12429816],
       [ 0.09587071,  0.82793611, -0.13187869, -1.70646665]])

In [27]:
import numpy as np
np.random.randint(1,100)


57

In [28]:
import numpy as np
#generates 10 random 
#integers between 1 to 100
np.random.randint(1,100,10)

array([90,  5,  2, 38, 45, 79, 57, 73,  1, 84])

In [29]:
import numpy as np
#define
arr = np.arange(16)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
import numpy as np
#define
arr = np.arange(16)
#show
arr
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr

array([19, 10, 11,  7, 21, 35, 26,  1, 10, 24])

In [32]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr
random_arr.max()


45

In [33]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr
random_arr.max()
random_arr.argmax()

2

In [34]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr
random_arr.max()
random_arr.argmax()
random_arr.min()


3

In [35]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr
random_arr.max()
random_arr.argmax()
random_arr.min()
random_arr.argmin()


2

In [36]:
import numpy as np
#define
random_arr = np.random.randint(0,50,10)
#show
random_arr
arr.shape

(16,)

In [37]:
arr.reshape(1,16)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [38]:
arr.reshape(1,16).shape


(1, 16)

In [39]:
arr.reshape(16,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [40]:
arr.reshape(16,1).shape


(16, 1)

In [41]:
arr.dtype


dtype('int32')

In [42]:
#Get a value 
#at an index
arr[5]


5

In [43]:
#Get values 
#in a range
arr[1:5]

array([1, 2, 3, 4])

In [44]:
#Setting a value with
#index range
arr[0:5]=100#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [45]:
#Reset array, we'll 
#see the reason behind it soon
arr = np.arange(0,11)#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
slice_of_arr = arr[0:6]#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
#Change Slice
slice_of_arr[:]=99#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
a = [[1,2,3],[4,5,6]]#Converting to 
#numpy 2d array
np_a = np.array(a)#show
np_a


array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
#2 rows, 3 columns
np_a.shape

(2, 3)

In [53]:
b = [100,200,300]#converting to 
#numpy array
np_b = np.array(b)#show
np_b

array([100, 200, 300])

In [54]:
np_b.shape

(3,)

In [55]:
np_b_reshaped = np_b.reshape(1,3)#show
np_b_reshaped

array([[100, 200, 300]])

In [56]:
#1 row, 3 columns
np_b_reshaped.shape

(1, 3)

In [57]:
np_a + np_b_reshaped

array([[101, 202, 303],
       [104, 205, 306]])

In [58]:
np.array([[100,200,300],[100,200,300]])

array([[100, 200, 300],
       [100, 200, 300]])

In [59]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))#Show
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
#Indexing row
arr_2d[1]


array([4, 5, 6])

In [61]:
#Getting individual element value
arr_2d[1][0]


4

In [62]:
#another way
arr_2d[1,0]

4

In [71]:
arr_2d[:2, 1:]  # Correct slicing for the top right corner





array([[2, 3],
       [5, 6]])

In [70]:
#Shape of the 
#bottom row
arr_2d[2]


array([7, 8, 9])

In [72]:
arr1 = np.arange(1,11)#show
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr1 > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
bool_arr = arr1 > 5#show
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr1[bool_arr]


array([ 6,  7,  8,  9, 10])

In [76]:
arr1[arr1 > 2]


array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr2 = np.arange(0,10)
arr2 + arr2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
arr2 * arr2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [80]:
arr2 - arr2


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr2 / arr2


C:\Users\hp\AppData\Local\Temp\ipykernel_9100\3151952473.py:1: RuntimeWarning: invalid value encountered in divide
  arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [82]:
1 / arr2


C:\Users\hp\AppData\Local\Temp\ipykernel_9100\1481894037.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [83]:
arr2 ** 3


array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [84]:
np.sqrt(arr2)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr2)


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
np.max(arr2)


9

In [87]:
np.sin(arr2)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [88]:
np.log(arr2)


C:\Users\hp\AppData\Local\Temp\ipykernel_9100\3827996858.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr2)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [90]:
import time
import numpy as np

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)  # dot product of two vectors
toc = time.time()

print("Time taken in vectorized version: " + str(1000 * (toc - tic)) + " ms")  # Corrected string formatting


Time taken in vectorized version: 199.8136043548584 ms


In [92]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print("Time taken in for loop version: " + str(1000 * (toc - tic)) + " ms")  # Corrected string formatting


Time taken in for loop version: 690.1640892028809 ms
